### ISSUE TITLE
a syntax highlight mistake

### ISSUE THREAD

**Issue by ailisp** [serialhex/language-common-lisp#4]
A variable named `js-cond` mistake in highlight: `cond` is marked as keyword. And a symbol `bar` in the package `foo` will show as `foo:bar`, with `:bar` highlighted as the same color as keyword parameters. Maybe only `bar` highlighted is better.

**Comment by serialhex** [comment]
Yeah, these are some errors that I'm going to fix the regex's on.  There is also the case of things like `if-let` the `if` part is highlighted and some other wonkyness.  I'll get to it but it's not terribly high on the priority (as there is more than a few cases of this).

But thank you for pointing it out (and if you happen to have some free time and want to fix up some regexes, me and probably many others would be very greatful to make a pull request!!!)

**Comment by serialhex** [comment]
Thank you!  I pulled in your patch & pushed a new version.  If you were in town I'd buy you a beer!
